all:
  stylesheets: [frontend/modules/search.css]
  components:
    sidebar_300: [global, sidebar300]

indexSuccess:
  javascripts: [jquery/masonry.js, jquery/infinitescroll.js]
  components:
    sidebar_160: [search, sidebar]

indexNoResults:
  components:
    sidebar_300: [search, sidebar]
