guideToCollectingSuccess:
  stylesheets: [frontend/modules/splash.css]
  components:
    footer:  []
    breadcrumbs: []

guideDownloadSuccess:
  stylesheets: [frontend/modules/splash.css]
  components:
    footer:  []
    breadcrumbs: []

guideDownloadAlert:
  stylesheets: [frontend/modules/splash.css]
  components:
    footer:  []
    breadcrumbs: []


wordPressFeaturedItemsSuccess:
  javascripts: [jquery/expander.js, jquery/masonry.js]
  components:
    sidebar_300:  [misc, sidebarWordPressFeaturedItems]
