# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/09-Cache

default:
  enabled:     false
  with_layout: false
  lifetime:    86400

_ad_slots:
  enabled:     true
  with_layout: false
  lifetime:    3600

_header:
  enabled:     true
  contextual:  false
  with_layout: false
  lifetime:    300

_javascripts:
  enabled:     false
  contextual:  true
  with_layout: false
  lifetime:    3600

# We cannot cache the footer because of the signup form and the _csrf_token
_footer:
  enabled:     false

_footer_links:
  enabled:     true
  with_layout: false
  lifetime:    84600
