# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/12-Filters

rendering: ~

#ssl:
#  class: cqSslRedirectFilter
#remember_me:
#  class: cqCollectorRememberMeFilter
#uuid:
#  class: cqUuidFilter
security:
  class: cqSecurityFilter
#seo:
#  class: iceSeoFilter
#history:
#  class: iceRequestHistoryFilter
#visitorInfo:
#  class: cqVisitorInfoFilter
#admin_cache:
#  class: cqConditionalCacheFilter

cache: ~
execution: ~
