signupSuccess:
  javascripts: [jquery/pstrength.js]
  stylesheets: [legacy/forms.css]
  components:
    sidebar: [general, sidebar]

packagesSuccess:
  stylesheets: [legacy/forms.css, legacy/package.css]
  components:
    sidebar: []
